image: gitpod/workspace-full:latest
tasks:
  - init: rustup toolchain update stable && rustup component add rust-src rustc-dev llvm-tools-preview && cd cargo-oj && cargo install --path . && cargo install cargo-boj
