[package]
name = "cargo-boj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.10", features = ["blocking", "cookies"] }
fantoccini = "0.19"
tokio = { version = "1", features = ["full"] }
serde_json = "1"
scraper = "0.13"
directories = "4"